#!/usr/bin/env sh

# Запустить Prettier для форматирования файлов
echo "Running Prettier..."
npm run format

# Запустить ESLint для проверки JavaScript и TypeScript файлов
echo "Running ESLint..."
npm run lint:js

# Запустить Stylelint для проверки CSS и SCSS файлов
echo "Running Stylelint..."
npm run lint:css

# Проверка коммита с использованием commitlint
echo "Validating commit message..."
npx commitlint --edit $1

echo "Pre-commit hook is running"